name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # on job level this will cause GitHub actions to continue executing jobs, that are related to the matrix, even when some jobs fail.
    # with a matrix you can run the same job with different configurations e.g different runners, different node config etc.
    strategy:
      matrix: # run the same job with different configurations
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # reserved keyword to add a list of key values as single combinations (stand alone combination)
                 # here node version 18 will be used only with latest ubuntu os
          - node-version: 18
            operating-system: ubuntu-latest
        exclude: # reserved keyword to exclude combinations (alternative for include)
                 # here node version 12 will not be used with latest windows os
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }} # use expression syntax to dynamically configure operating system. Runs build job multiple times (once per array value).
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build