name: Reusable Deploy
on: workflow_call # make this workflow usable on other workflows with event workflow_call. Other workflows will run this workflow.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying & uploading..."